global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'docker-swarm'
    environment: 'production'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  # - "alerts/*.yaml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'vector-agent'
    static_configs:
      - targets: ['vector-agent:9598']

  - job_name: 'vector-aggregator'
    static_configs:
      - targets: ['vector-aggregator-1:9598', 'vector-aggregator-2:9598']
      # - targets: ['host.docker.internal:9598']
